apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: default
stringData:
  SMTP_USERNAME: ENC[AES256_GCM,data:lqNL40Yq77KwZlKNw1k9e17CKudGa6gaiQ==,iv:zdFYnfB3E+34GqokGsOBYoXaMU+swAILMfU+j3Jifu8=,tag:n414/VZ79zoFBCtWjlNIQg==,type:str]
  SMTP_PASSWORD: ENC[AES256_GCM,data:8Bey6lzDTL7BUdnxTIH2DQ==,iv:uQCiJRq3B2fI+uxHg7igeAZLcbulYrtug2NmXWCNfWk=,tag:pi4JhkORIt+9TU01ROg+ew==,type:str]
  ADMIN_TOKEN: ENC[AES256_GCM,data:FxTAJbdRdTBw+v4ZmWzEP5lnb8Tmyal+gEQUm+OfxHEsKgE6EoAkyQWSUljQ53MXjf+47cWJN8N/Y5g2n8y7SJLQfkXWs8ApQtYR2hpDxbGKpUbnClwBP99OAr3ash2tXVjIc32MyQIcEOmbP8Vn7+j1eBob9aXhKKvrO04PkoWVtmtVDzE=,iv:jTr8o9xx6dqF2mipCmSKsNVXMffMm4WoITqzSnzLdOk=,tag:r5RkML0+qq2CGq9vVmtOJg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18j5s9lnthmfa892eyu75glemdf69y08a5wwszgsfud06fqjpp37qgzhddc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWKzc4bmFlQWhoOFNXZWo3
        ellnZGtDUTJaVjdhWVJlMnllNTl3ZHhKQzM0CmpiSms5L0lhWFNFK2svalkzVnhZ
        Q1puMFQzT1ZJQWUrRWxOcHgxSzlIQ1UKLS0tIERtVURSaldtWXJJWVVEOUo0WktI
        L3VFMkNxSjBCcEMrVHUyZ0JiZk9mRGsKenstE3cbzKNBcOHsiSA5xMoLmi4z8DGi
        mHkarcxtIfGx2gFIdJmkwtuuLd7ZVsN3OhA7IE/hpPYjPa9PDS44kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-26T23:49:51Z"
  mac: ENC[AES256_GCM,data:kL+dRcLSWP32HEtLjSnIAFtqpHS7srdQYVM/wkj9kgZvmyrJQZeuJBDyPjfuwNLSMd/6W0Njb8PGHiq5oRj0rmUTgAyLeMS+BubYjzdllUh+lNNZthZLzSx98f4vmKtslssMHXOoefcrHK1Ysn/Fml9lZkJjLP7q2kN3NWiBwhk=,iv:tn6Kk6y8+cpyQmuC+RP7wp84COPaEWtMgLPClsZTlpM=,tag:pAgVkNlPqgWJItDOdv2/VA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
