# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: vaultwarden-secrets
  namespace: default
stringData:
  SMTP_USERNAME: youremail@gmail.com
  SMTP_PASSWORD: yourgmailapppassword
  ADMIN_TOKEN: youradmintokenforvaultwarden
