---
creation_rules:
  - path_regex: talos/.*\.sops\.ya?ml
    mac_only_encrypted: true
    age: "age18j5s9lnthmfa892eyu75glemdf69y08a5wwszgsfud06fqjpp37qgzhddc"
  - path_regex: (bootstrap|kubernetes)/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    mac_only_encrypted: true
    age: "age18j5s9lnthmfa892eyu75glemdf69y08a5wwszgsfud06fqjpp37qgzhddc"
stores:
  yaml:
    indent: 2
