# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nsXjKqba3xLFFixeHOWe86TGSM2ijSxjsvb3IojMioY=,iv:A4KrpdkQJtnBPbrQkuRKwHnKRyfIf6IJirULdlVwFqA=,tag:A4Yv9I2dWn582fY6QRMbaw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18j5s9lnthmfa892eyu75glemdf69y08a5wwszgsfud06fqjpp37qgzhddc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCc2ZXblpwcUtxNisxREwv
        MVlvYlhQVThXR09LQXo5Z1cyc1BjTitINlZRCkg2dytGdFdLckhqallSR1ljSUVZ
        bStoSjRrUWtRelphcWNMbUJXWWMrbEUKLS0tIFFjLzNHNlRpWFIyUVBlamcrbGla
        YXZGN0RDZjlmVmpRZDM5bFJmekN4QUEK3jwqb/FhpuTRgYFBCydp6Toqp2SOsTSa
        LJqX1eyQKLxGURD0DqcsKfmDJ7BpqQGEJ8b1tBiaql1r4RUoOQRbnw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T03:41:57Z"
  mac: ENC[AES256_GCM,data:R4iERGdCUuZuB+hRZoq7mMlLEq/WUJ2bYLdBsSI+iPxi7g1BQlViBS+fOTql6PGgV3lEYL1dP3XnrPUa0jjEeYtZ12XTjhS7vz8ZDUZreOJawdvIzTv/ebA4yqRFIslvHWt3BjjTKMjF9F/kjnpwz8bdO+OFU+x4SwfcPioadZo=,iv:PI0kHMWNK7lUUHLwyjZK5H2W3kraQ7E+W6Lg7dRPMro=,tag:xuAIsB7/ApMf4oC/O3oWLg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
