---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-secret
  namespace: external-secrets
stringData:
  1password-credentials.json: op://homelab-cluster/homelab-cluster/OP_CREDENTIALS_JSON
  token: op://homelab-cluster/homelab-cluster/OP_CONNECT_TOKEN

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword
spec:
  provider:
    onepassword:
      connectHost: http://homelab-cluster.external-secrets.svc.cluster.local
      vaults:
        homelab-cluster: 1
      auth:
        secretRef:
          connectTokenSecretRef:
            key: token
            name: onepassword-secret
            namespace: external-secrets
