apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:joIRgHcXKKpBVIHaQmVTtlEcVki0ZqtJRauDB0M6Pjhu/409yw53juwGiL/4L1IM8LzYazL97xfTze54m+fFAnZIJjJSNbNErCj2,iv:Rev9gkDfaAbAeEMMbduviNl4ci39brhhtl4dgl026TM=,tag:Bp4PH3DVg44k7CHI0TbARw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age18j5s9lnthmfa892eyu75glemdf69y08a5wwszgsfud06fqjpp37qgzhddc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORXR4SnJHQTFkbG5qTkNa
        cUZzM0dlcGlOdWlLdUdSWXEzL09ESjdqelVRCjMwcjR0OTB2aHFvbTJSeXJiVFI5
        aEF3YnZRSmhKRG5MaE5saFRhalZmeHMKLS0tIEJTQmRzODZTQVluYlU2UnB4Mzkx
        WnU1SDEvclNTWWtvejBCakdycXFsUW8KW78mG6WJ7tZKT4WEKN/RHiKb3Uhx9tUh
        /5Ah2UnQ7SWMh01FVLRI945maZq5RiUw3hVQNM+udTg7woqXLUC7qQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-25T03:41:58Z"
  mac: ENC[AES256_GCM,data:tN5UUxLQ/MHQhBP1NMlOdEQHQEB0toKcKYk9xWfkVlm81nI8OHPQ5G4wGau00IfTlYHIPIseQ8RhAB8HhsBH8VVS+EkCSvRKJgJ72kRY5hk5OTOInN9/ld2mxwrEngQisfi1P0YWDEOXbWzIljb+C9mqEef4vc7CXUjcLPxshfM=,iv:VVne2Y70HSMjFGjh6Ot1zdyFy8lnWF2xutTU2EICxGY=,tag:0/b860yoXxTWt5SDKACy/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
