---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.2.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    localpv-provisioner:
      enabled: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: false
    mayastor:
      enabled: true
      csi:
        enabled: true
      operator:
        enabled: true
      storagePools:
        - name: pool-1
          disks: ["/dev/sdb"]  # Replace with your disk path
          nodeSelector:
            kubernetes.io/hostname: node-1  # Replace with your node name
      nvmf:
        enabled: true
        replicaCount: 2
      resources:
        mayastor:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"
        mayastor-csi:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
